# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIeFzIUQinDVKm6xWc0U_hm73DwhZy7i
"""

import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 102, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Bob', 'Eve', np.nan],
    'Join_Date': ['2023-01-15', '2023/02/20', '15-03-2023', '2023-04-10', '2023/02/20', '2023-05-05', '2023-06-01'],
    'Salary': ['50000', '$60,000', '70000', np.nan, '$60,000', '85000', '90000'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'IT', 'hr', 'Finance']
}
df_raw = pd.DataFrame(data)
df_raw.to_csv('messy_employee_data.csv', index=False)
print(" Created 'messy_employee_data.csv' successfully.\n")

def clean_data_pipeline(file_path):
    print("--- Starting Data Cleaning Pipeline ---")
    df = pd.read_csv(file_path)
    print(f"Original Data Shape: {df.shape}")

def clean_data_pipeline(file_path):
    print("--- Starting Data Cleaning Pipeline ---")
    df = pd.read_csv(file_path)
    print(f"Original Data Shape: {df.shape}")
    # Removed the recursive call: clean_data_pipeline('messy_employee_data.csv')
    df = df.drop_duplicates()
    print("-> Duplicates removed.")


    df = df.dropna(subset=['Name'])

    df['Salary'] = df['Salary'].astype(str).str.replace(r'[$,]', '', regex=True)
    df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')


    median_salary = df['Salary'].median()
    df['Salary'] = df['Salary'].fillna(median_salary)
    print("-> Missing values handled and Salary formatted.")


    df['Department'] = df['Department'].str.upper()
    print("-> Text capitalization standardized.")


    df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce', dayfirst=False)
    print("-> Dates standardized.")


    print(f"Final Data Shape: {df.shape}")
    return df


df_cleaned = clean_data_pipeline('messy_employee_data.csv')

print("\n--- Final Cleaned Data Preview ---")
print(df_cleaned)

df_cleaned.to_csv('cleaned_employee_data.csv', index=False)
print("\n Cleaned dataset saved as 'cleaned_employee_data.csv'")